# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d05e6d361619b0464d8ec4752671874a42a8c49cba9f563f3aae35027a94151195b2788f1d485d8b9c0b2b1bc2442fc8308bf11b0f3f099a614de8f90d670b0e

test:
  secret_key_base: 6b98840e19f64ecdce6b436dedceca1c1352bf5175ff93913ffa00548f87f5e632d3624c5228c4806f933ef871f2f92749bc6762dd85090d384cd874dff9a097

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
